Buffer pool page_hash_locks optimization
kunpengcompute/mysql-server pull request #126
Opened 2021-07-29 01:58 UTC by Winston-leon

1. Make system variable page_hash_locks configurable
2. Make the maximum value of system variable page_hash_locks larger

2021-07-29 02:05 UTC, zwang28 requested changes

2021-07-29 02:05 UTC, zwang28 commented on storage/innobase/handler/ha_innodb.cc
>                            nullptr, nullptr, 16, 1, MAX_PAGE_HASH_LOCKS, 0);
应维持默认值不变（1024）

2021-07-31 02:42 UTC, bzhaoopenstack commented
@Winston-leon Hi, could you please to sign a kunpengcompute CLA? This is a constant check in this repo now. Thanks for your cooperation. ;-)

2021-07-31 06:53 UTC, zwang28 approved these changes

2021-08-10 04:30 UTC, liuwei-ck approved these changes

2021-08-10 04:32 UTC, merged