Kp 8.0 thread pool dev kp
kunpengcompute/mysql-server pull request #168
Opened 2021-10-09 01:54 UTC by nbuxrr

#166 
Adding thread pool connector for mysql 8.0.20

2021-10-09 02:42 UTC, zwang28 commented on sql/threadpool_unix.cc
> +    /* The remaining threads can be created at most */
前文这段注释需要相应修改 ”We generally try to keep one thread per group active...“

2021-10-09 02:42 UTC, zwang28 commented on sql/threadpool_unix.cc
> +    /* The remaining threads can be created at most */
当前listener_picks_event == true时就不走这段逻辑了

2021-10-09 02:42 UTC, zwang28 commented on sql/threadpool_unix.cc
> +          In order to achieve the best running performance of the
这句注释不适用了，应删除”Wake failed, hence groups has no idle threads. Now check if there are any threads in the group except listener.“

2021-10-09 02:49 UTC, zwang28 commented on sql/threadpool_unix.h
> +// #include <my_global.h>
不用的代码行删除，不要注释

2021-10-09 02:49 UTC, zwang28 commented on sql/threadpool_unix.cc
> +// #ifdef __linux__
不用的代码行删除，不要注释

2021-10-09 06:36 UTC, yibantianxia approved these changes

2021-10-09 06:36 UTC, yibantianxia commented on sql/threadpool_unix.cc
> +static int io_poll_wait(int pollfd, struct kevent *events, int maxevents,
和static int io_poll_wait(int pollfd, native_event *events, int maxevents,
                        int timeout_ms) noexcept {相似度很高。

2021-10-09 06:52 UTC, yibantianxia approved these changes

2021-10-09 06:52 UTC, yibantianxia commented on sql/sql_parse.cc
> +    break;
break没有缩进

2021-10-09 06:52 UTC, yibantianxia commented on sql/threadpool_unix.cc
> +{
{不需要另起一行

2021-10-09 06:52 UTC, yibantianxia commented on sql/thread_pool_info.cc
> +  {
{不用另起一行

2021-10-09 06:52 UTC, yibantianxia commented on sql/thread_pool_info.cc
> +      {
{不用另起一行

2021-10-09 07:13 UTC, PeterWeiWang commented on sql/threadpool_unix.h
> +/* Copyright (C) 2012 Monty Program Ab
头文件未加华为版本申明

2021-10-09 07:13 UTC, PeterWeiWang commented on sql/threadpool_unix.cc
> +/* Copyright (C) 2012 Monty Program Ab
头文件未加华为版权申明

2021-10-09 07:53 UTC, zwang28 requested changes

2021-10-09 07:53 UTC, zwang28 commented on sql/threadpool_unix.cc
> +  while (1) {
while (true)

2021-10-09 07:53 UTC, zwang28 commented on sql/threadpool_unix.cc
>      wake_or_create_thread(thread_group, connection->thd->is_admin_connection());
可能发生：即便admin connection在优先队列了，但是没有worker线程去处理它

2021-10-09 08:05 UTC, zwang28 commented on sql/threadpool_unix.cc
> +      mysql_mutex_unlock(&thread_group->mutex);
这两行没必要

2021-10-09 08:28 UTC, PeterWeiWang commented on sql/sql_client.cc
> +  net->read_timeout = net->write_timeout = 0;
分开赋值

2021-10-09 08:28 UTC, PeterWeiWang commented on sql/sql_thd_api.cc
> +  if (!thd) {
指针用nullptr来判空

2021-10-09 08:28 UTC, PeterWeiWang commented on sql/threadpool_unix.cc
> +    {
{不用另起一行

2021-10-09 08:28 UTC, PeterWeiWang commented on sql/threadpool_unix.cc
> +  if (err)
有else分支，必须加大括号

2021-10-09 08:28 UTC, PeterWeiWang commented on sql/threadpool_unix.cc
> +
注释和函数之间不要留空行

2021-10-09 08:28 UTC, PeterWeiWang commented on sql/threadpool_unix.cc
> +  if (group != connection->thread_group) {
if条件可以合并

2021-10-09 08:28 UTC, PeterWeiWang commented on sql/threadpool_unix.cc
> +       i < array_elements(all_groups) && (all_groups[i].pollfd >= 0); i++) {
array_elements(all_groups)提取到循环外

2021-10-09 08:28 UTC, PeterWeiWang commented on sql/threadpool_unix.cc
> +  static bool msg_written;
显式初始化

2021-10-09 09:14 UTC, zwang28 commented on sql/threadpool_unix.cc
>  inline bool too_many_busy_threads(const thread_group_t &thread_group) noexcept {
需修改函数注释

2021-10-11 01:26 UTC, zwang28 commented on sql/threadpool_unix.cc
> +    int workers_in_need = (int)threadpool_toobusy -
依据toobusy还是oversubscribed，怎么决定的

2021-10-11 01:38 UTC, nbuxrr commented on sql/sql_parse.cc
> +    break;
break在{}外面 不需要缩进

2021-10-11 01:40 UTC, nbuxrr commented on sql/threadpool_unix.cc
> +/* Copyright (C) 2012 Monty Program Ab
移植文件

2021-10-11 07:45 UTC, PeterWeiWang commented on sql/threadpool_unix.cc
> +// struct thread_group_t;
去除无用代码

2021-10-18 02:00 UTC, zwang28 requested changes

2021-10-18 03:10 UTC, nbuxrr commented on sql/sql_client.cc
> +  net->read_timeout = net->write_timeout = 0;
percona引入格式

2021-10-18 03:22 UTC, nbuxrr commented on sql/threadpool_unix.cc
> +  if (group != connection->thread_group) {
利于可读

2021-10-18 03:30 UTC, zwang28 approved these changes

2021-10-18 03:35 UTC, liuwei-ck approved these changes

2021-10-18 03:37 UTC, merged